-- Your SQL goes here
CREATE TABLE groups (
  id SERIAL PRIMARY KEY,
  app_id SERIAL NOT NULL REFERENCES apps(id) ON DELETE CASCADE ON UPDATE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);