-- Your SQL goes here
CREATE TABLE app_keys (
  id SERIAL PRIMARY KEY,
  app_id SERIAL NOT NULL REFERENCES apps(id) ON DELETE CASCADE ON UPDATE CASCADE,
  key_preview VARCHAR(255) NOT NULL,
  key VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);