-- Your SQL goes here
CREATE TABLE integrations (
  id SERIAL PRIMARY KEY,
  service SMALLINT NOT NULL,
  group_id SERIAL NOT NULL REFERENCES apps(id) ON DELETE CASCADE ON UPDATE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);